- hosts: webserver

  tasks:
    - name: install mc
      ansible.builtin.apt:
        name: mc
        state: present
        update_cache: yes
      become: yes
    - name: delete mc
      ansible.builtin.apt:
        name: mc
        state: absent
      become: yes
